//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace simpleTestingSystem.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("simpleTestingSystem.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить новый ответ.
        /// </summary>
        internal static string ADD_ANSWER {
            get {
                return ResourceManager.GetString("ADD_ANSWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить новый вопрос.
        /// </summary>
        internal static string ADD_QUESTION {
            get {
                return ResourceManager.GetString("ADD_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внимание!.
        /// </summary>
        internal static string ATTENTION {
            get {
                return ResourceManager.GetString("ATTENTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить вопрос.
        /// </summary>
        internal static string CHANGE_QUESTION {
            get {
                return ResourceManager.GetString("CHANGE_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на currentUser.
        /// </summary>
        internal static string CURRENT_USER {
            get {
                return ResourceManager.GetString("CURRENT_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать ответа.
        /// </summary>
        internal static string EDIT_ANSWER {
            get {
                return ResourceManager.GetString("EDIT_ANSWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка!.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отлично.
        /// </summary>
        internal static string EXCELLENT_MARK {
            get {
                return ResourceManager.GetString("EXCELLENT_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл с тестами не найден, либо повреждён!.
        /// </summary>
        internal static string FILE_NOT_FOUNT_OR_DAMAGED {
            get {
                return ResourceManager.GetString("FILE_NOT_FOUNT_OR_DAMAGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на questions.dat.
        /// </summary>
        internal static string FILE_QUESTIONS {
            get {
                return ResourceManager.GetString("FILE_QUESTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на users.dat.
        /// </summary>
        internal static string FILE_USERS {
            get {
                return ResourceManager.GetString("FILE_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо выбрать вариант ответа.
        /// </summary>
        internal static string NEED_SELECTED_ANSWER {
            get {
                return ResourceManager.GetString("NEED_SELECTED_ANSWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удовлетворительно.
        /// </summary>
        internal static string SATISFACTORILY_MARK {
            get {
                return ResourceManager.GetString("SATISFACTORILY_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход выполнен!\nДобрый день,{1} {0}!.
        /// </summary>
        internal static string SUCCESS_LOGIN {
            get {
                return ResourceManager.GetString("SUCCESS_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вопросы успешно сохранены!.
        /// </summary>
        internal static string SUCCESS_SAVED_QUESTIONS {
            get {
                return ResourceManager.GetString("SUCCESS_SAVED_QUESTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неудовлетворительно.
        /// </summary>
        internal static string UNSATISFACTORILY_MARK {
            get {
                return ResourceManager.GetString("UNSATISFACTORILY_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введёно имя пользователя уже используется другим пользователем.
        /// </summary>
        internal static string USERNAME_IS_ALREADY_EXIST {
            get {
                return ResourceManager.GetString("USERNAME_IS_ALREADY_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хорошо.
        /// </summary>
        internal static string WELL_MARK {
            get {
                return ResourceManager.GetString("WELL_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо заполнить поле вопрос, добавить минимум 2 ответа и выбрать один правильный ответ.
        /// </summary>
        internal static string WRONG_SET_QUESTION_FORM {
            get {
                return ResourceManager.GetString("WRONG_SET_QUESTION_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя пользователя или пароль не верны.
        /// </summary>
        internal static string WRONG_USER_NAME_OR_PASSWORD {
            get {
                return ResourceManager.GetString("WRONG_USER_NAME_OR_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваш результат - {0}.
        /// </summary>
        internal static string YOUR_RESULT {
            get {
                return ResourceManager.GetString("YOUR_RESULT", resourceCulture);
            }
        }
    }
}
