//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace simpleTestingSystem.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.53")]
        public double SATISFACTORILY_MARK_BUTTOM_RANGE {
            get {
                return ((double)(this["SATISFACTORILY_MARK_BUTTOM_RANGE"]));
            }
            set {
                this["SATISFACTORILY_MARK_BUTTOM_RANGE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.8")]
        public double SATISFACTORILY_MARK_UPPER_RANGE {
            get {
                return ((double)(this["SATISFACTORILY_MARK_UPPER_RANGE"]));
            }
            set {
                this["SATISFACTORILY_MARK_UPPER_RANGE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.8")]
        public double WELL_MARK_BUTTOM_RANGE {
            get {
                return ((double)(this["WELL_MARK_BUTTOM_RANGE"]));
            }
            set {
                this["WELL_MARK_BUTTOM_RANGE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.93")]
        public double WELL_MARK_UPPER_RANGE {
            get {
                return ((double)(this["WELL_MARK_UPPER_RANGE"]));
            }
            set {
                this["WELL_MARK_UPPER_RANGE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.93")]
        public double EXCELLENT_MARK_BUTTOM_RANGE {
            get {
                return ((double)(this["EXCELLENT_MARK_BUTTOM_RANGE"]));
            }
            set {
                this["EXCELLENT_MARK_BUTTOM_RANGE"] = value;
            }
        }
    }
}
